// ============================================================================
// Strategy OS — extracted legacy implementation (REFERENCE ONLY, still live)
// ============================================================================
// This file is the working-instructions doc's Step 2: a mechanical extraction of
// Strategy OS's inline implementation out of index.html, moved here verbatim (not one
// character of logic changed) and loaded back via a single <script src="strategy-app.js">
// tag in exactly the spot the old inline <script> block used to sit. Functionally this
// changes nothing — Strategy OS keeps running exactly as it did the moment before this
// extraction, same globals, same DOM, same behavior.
//
// Why extract it at all, if nothing about its behavior changes: this file's real value is
// as a specification. It is the one artifact that names, in one place, every point where
// Strategy OS touches the rest of Hub — every global it reads or writes, every DOM node
// it expects to exist, every function defined elsewhere it calls. The full inventory of
// those touchpoints lives in docs/strategy-os-touchpoints.md, generated by reading this
// file end to end. The new React + TypeScript + Vite app at apps/strategy/ is being built
// FROM that inventory, replacing every one of these touchpoints deliberately rather than
// inheriting them by accident.
//
// This file will not survive the rewrite. Once apps/strategy/ replaces what's here, this
// file (and the /* legacy nav entry pointing at it, kept for a month as a rollback path)
// gets deleted — see the working-instructions doc's "Rollback" section. Do not build new
// features on top of this file; it exists to be read, inventoried, and eventually removed,
// not extended.
// ============================================================================

  (function(){
    "use strict";

    function esc(s){ return String(s==null?"":s).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];}); }
    function fmtDateTime(iso){
      if(!iso) return "—";
      try { return new Date(iso).toLocaleString("en-IN",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}); }
      catch(e){ return iso; }
    }
    function monthLabel(m){
      if(!m) return "—";
      var parts=m.split("-"); var d=new Date(Number(parts[0]), Number(parts[1])-1, 1);
      return d.toLocaleDateString("en-IN",{month:"long",year:"numeric"});
    }

    // Brands live in Firebase (strategy_brands/<id>) and are managed through the "Manage
    // brands" screen — see soRenderBrandList()/soRenderBrandForm() below. window._soBrandsCache
    // is kept live by soListenBrands().
    function soBrandList(){
      var brands = window._soBrandsCache || {};
      return Object.keys(brands).map(function(k){ return brands[k]; })
        .sort(function(a,b){ return (a.name||"").localeCompare(b.name||""); });
    }
    function soBrandName(id){
      var b = (window._soBrandsCache||{})[id];
      return b ? b.name : id;
    }

    var STAGE_ORDER = ["research", "strategy", "copy", "creative-direction", "deck-builder"];
    var STAGE_LABELS = {
      research: "Research", strategy: "Strategy", copy: "Copy",
      "creative-direction": "Creative direction", "deck-builder": "Deck",
    };
    var STATUS_LABELS = {
      draft: "Draft", queued: "Queued", locked: "Locked",
      running: "Running", repairing: "Repairing", needs_review: "Needs review",
      approved: "Approved", failed: "Failed", changes_requested: "Changes requested",
    };
    // Run-level status strings are always `${stageKey}_${state}` (pipeline.js's
    // runningStatus/reviewStatus, strategy-stage-approve.js's `${stage}_approved` /
    // `${stage}_changes_requested`) — build the display map from STAGE_ORDER once instead
    // of hand-listing every combination, so a new stage only needs adding to STAGE_ORDER.
    STAGE_ORDER.forEach(function(s){
      STATUS_LABELS[s + "_running"] = STAGE_LABELS[s] + " running";
      STATUS_LABELS[s + "_needs_review"] = "Needs review";
      STATUS_LABELS[s + "_changes_requested"] = "Changes requested";
      STATUS_LABELS[s + "_approved"] = STAGE_LABELS[s] + " approved";
    });

    // Plain-language phrase for the "Your next action" card (brief: "Use plain statuses
    // such as 'Researching,' 'Ready for review,' 'Creating copy,' and 'Building deck.'").
    // Keyed by stage, then by that stage's own status.
    var PLAIN_RUNNING_LABELS = {
      research: "Researching", strategy: "Writing strategy", copy: "Creating copy",
      "creative-direction": "Directing the shoot", "deck-builder": "Building deck",
    };
    // Same roster the backend uses to sign its "is on it" / "is fixing an issue" detail
    // text (pipeline.js's STAGE_AGENTS) — kept here too just for the emoji, so the headline
    // itself has a quick visual tell for which stage is running, at a glance.
    var STAGE_AGENT_EMOJI = {
      research: "👨🏻‍✈️", strategy: "🧕🏻", copy: "👩‍🎨",
      "creative-direction": "👩🏼‍🎤", "deck-builder": "👷🏾",
    };
    function plainActionPhrase(stage, status){
      if(status === "running") return PLAIN_RUNNING_LABELS[stage] || "Working";
      if(status === "repairing") return (PLAIN_RUNNING_LABELS[stage] || "Working") + " — fixing an issue";
      if(status === "needs_review") return "Ready for review";
      if(status === "changes_requested") return "Changes requested";
      if(status === "failed") return "Something went wrong";
      if(status === "locked") return "Waiting";
      if(status === "approved") return "Approved";
      return STATUS_LABELS[status] || status || "—";
    }
    function statusLabel(s){ return STATUS_LABELS[s] || s || "—"; }

    var _soRunsListener = null;   // strategy_runs (list view)
    var _soRunListener = null;    // strategy_runs/<runId> (detail view)
    var _soBrandsListener = null; // strategy_brands (brand list + name lookups everywhere)
    var _soOpenRunId = null;
    var _soBrandView = null;      // null | "list" | brandId being edited | "__new__"
    // Both the runs and brands listeners can re-render the run list underneath the "New
    // monthly strategy" modal (e.g. any run's status changing, or the brands listener's
    // very first real snapshot arriving after the modal is already open) — a full re-render
    // replaces #so-root's innerHTML, which recreates the modal fresh at its default
    // display:none and silently closes it out from under whoever has it open. Skip that
    // specific re-render while the modal is open; the cache itself is still kept current,
    // so the list catches up correctly the next time it's actually rendered.
    var _soNewRunModalOpen = false;
    var _soRunListView = "active"; // "active" | "archived"

    function soRoot(){ return document.getElementById("so-root"); }

    function soOpenPage(){
      _soOpenRunId = null;
      _soBrandView = null;
      _soRunListView = "active";
      if(_soRunListener){ _soRunListener.ref && _soRunListener.ref.off("value", _soRunListener.cb); _soRunListener=null; }
      soRenderRunList();
      soListenRuns();
      soListenBrands();
    }

    var _soBrandsCacheRaw = null;

    function soListenBrands(){
      if(!_db) return;
      if(_soBrandsListener){ _soBrandsListener.ref.off("value", _soBrandsListener.cb); }
      var ref = _db.ref("strategy_brands");
      var cb = function(snap){
        var val = snap.val() || {};
        var raw = JSON.stringify(val);
        if(raw === _soBrandsCacheRaw) return;
        _soBrandsCacheRaw = raw;
        window._soBrandsCache = val;
        if(_soOpenRunId || _soNewRunModalOpen) return; // run detail / open modal don't re-render here
        if(_soBrandView === "list") soRenderBrandList();
        else if(!_soBrandView) soRenderRunList(); // brand names shown in the run table + New Run picker
      };
      ref.on("value", cb);
      _soBrandsListener = { ref: ref, cb: cb };
    }

    var _soRunsCacheRaw = null; // last snapshot JSON — skip re-rendering the list when nothing actually changed

    function soListenRuns(){
      if(!_db) { soRoot().innerHTML = '<div class="note" style="margin-top:20px">Real-time sync isn\'t connected — Strategy OS needs Firebase to load runs.</div>'; return; }
      if(_soRunsListener){ _soRunsListener.ref.off("value", _soRunsListener.cb); }
      var ref = _db.ref("strategy_runs");
      var cb = function(snap){
        var val = snap.val() || {};
        // Firebase's real SDK only fires "value" when something actually changed, but a
        // polling stand-in (or a laggy connection re-delivering the same snapshot) can
        // fire repeatedly with identical data — re-rendering the whole table every time
        // yanks out from under an in-progress click on a row (Playwright surfaced this
        // directly: "element was detached from the DOM, retrying"). Skip the render
        // entirely when nothing changed instead of trying to out-run it.
        var raw = JSON.stringify(val);
        if(raw === _soRunsCacheRaw) return;
        _soRunsCacheRaw = raw;
        window._soRunsCache = val;
        // Also skip while the Manage Brands screen (list OR an open edit/add form) is
        // showing — _soBrandView is non-null for either. Without this, a run update
        // arriving while someone's mid-edit on a brand form (e.g. a background research
        // job's own writes, same as the run this file's own e2e test starts) replaced the
        // form with the run list out from under them — the exact same
        // "element was detached from the DOM" symptom the comment above already fixed for
        // the run list's own clicks, just via a different trigger onto the same #so-root.
        if(!_soOpenRunId && !_soNewRunModalOpen && !_soBrandView) soRenderRunList();
      };
      ref.on("value", cb);
      _soRunsListener = { ref: ref, cb: cb };
    }

    function soRunList(){
      var runs = window._soRunsCache || {};
      return Object.keys(runs).map(function(k){ return runs[k]; })
        .sort(function(a,b){ return (b.createdAt||"").localeCompare(a.createdAt||""); });
    }

    function soIsArchived(r){ return !!(r && r.archivedAt); }

    function soSetRunListView(view){
      _soRunListView = view;
      soRenderRunList();
    }

    function soRenderRunList(){
      var root = soRoot(); if(!root) return;
      var allRuns = soRunList();
      var activeRuns = allRuns.filter(function(r){ return !soIsArchived(r); });
      var archivedRuns = allRuns.filter(soIsArchived);
      var viewingArchived = _soRunListView === "archived";
      var runs = viewingArchived ? archivedRuns : activeRuns;

      var rows = runs.map(function(r){
        var actions = viewingArchived
          ? '<button class="btn btn-ghost" style="padding:4px 12px;font-size:11px" onclick="event.stopPropagation();window.soOpenRun(\''+esc(r.runId)+'\')">Open</button>'+
            '<button class="btn btn-ghost" style="padding:4px 12px;font-size:11px" onclick="event.stopPropagation();window.soRestoreRun(\''+esc(r.runId)+'\')">Restore</button>'+
            '<a href="#" style="font-size:11px;color:var(--muted);align-self:center" onclick="event.preventDefault();event.stopPropagation();window.soPurgeRun(\''+esc(r.runId)+'\')">Purge permanently</a>'
          : '<button class="btn btn-ghost" style="padding:4px 12px;font-size:11px" onclick="event.stopPropagation();window.soOpenRun(\''+esc(r.runId)+'\')">Open</button>'+
            '<button class="btn btn-ghost" style="padding:4px 12px;font-size:11px" onclick="event.stopPropagation();window.soArchiveRun(\''+esc(r.runId)+'\')">Archive</button>';
        return '<tr style="cursor:pointer" onclick="window.soOpenRun(\''+esc(r.runId)+'\')">'+
          '<td>'+esc(soBrandName(r.brandId))+'</td>'+
          '<td>'+esc(monthLabel(r.month))+'</td>'+
          '<td>'+esc(STAGE_LABELS[currentStageOf(r)] || '—')+'</td>'+
          '<td>'+esc(statusLabel(r.status))+'</td>'+
          '<td>'+esc(r.owner||'—')+'</td>'+
          '<td>'+esc(fmtDateTime(r.updatedAt))+'</td>'+
          '<td style="display:flex;gap:6px">'+actions+'</td>'+
        '</tr>';
      }).join("");

      var brands = soBrandList();
      root.innerHTML =
        '<div class="section-header" style="margin-top:0">'+
          '<div class="section-title">Strategy OS</div>'+
          '<div style="display:flex;gap:8px">'+
            '<button class="btn btn-ghost" onclick="window.soOpenBrandList()">Manage brands</button>'+
            '<button class="btn btn-primary" onclick="window.soOpenNewRunModal()">+ New monthly strategy</button>'+
          '</div>'+
        '</div>'+
        // Additive, not a cutover — the rewrite (see docs/strategy-os-touchpoints.md and
        // the working-instructions doc) has full parity now, but this stays a link rather
        // than replacing this tab outright, matching the doc's own rollback provision
        // (the old implementation stays reachable at /strategy-old/ for a month). Whoever
        // decides to make /strategy/ the default just needs to update Hub's own nav
        // click handler for this tab — nothing here depends on that decision either way.
        '<div class="note" style="margin-bottom:14px">Rebuilt in React — <a href="/strategy/" style="color:var(--accent)">try the new Strategy OS &rarr;</a></div>'+
        '<div class="att-board">'+
          '<div class="bh" style="display:flex;align-items:center;gap:10px">'+
            '<span>Strategy runs<span class="tag">'+runs.length+'</span></span>'+
            '<span style="display:flex;gap:6px;margin-left:auto">'+
              '<button class="btn '+(viewingArchived?'btn-ghost':'btn-primary')+'" style="padding:4px 12px;font-size:11px" onclick="window.soSetRunListView(\'active\')">Active ('+activeRuns.length+')</button>'+
              '<button class="btn '+(viewingArchived?'btn-primary':'btn-ghost')+'" style="padding:4px 12px;font-size:11px" onclick="window.soSetRunListView(\'archived\')">Archived ('+archivedRuns.length+')</button>'+
            '</span>'+
          '</div>'+
          (runs.length
            ? '<div class="scroll"><table class="att-tbl wide"><thead><tr><th>Client</th><th>Month</th><th>Current stage</th><th>Status</th><th>Owner</th><th>Last updated</th><th></th></tr></thead><tbody>'+rows+'</tbody></table></div>'
            : '<div class="note">'+(viewingArchived ? 'No archived runs.' : 'No strategy runs yet — start the first one.')+'</div>')+
        '</div>'+
        '<div id="so-new-run-modal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:600;align-items:center;justify-content:center">'+
          '<div style="background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:22px;width:340px;max-width:92vw">'+
            '<div style="font-weight:700;margin-bottom:14px">New monthly strategy</div>'+
            (brands.length
              ? '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Client</label>'+
                '<select class="form-control" id="so-new-brand" style="margin-bottom:12px">'+
                  brands.map(function(b){ return '<option value="'+esc(b.id)+'">'+esc(b.name)+'</option>'; }).join("")+
                '</select>'
              : '<div class="note" style="margin-bottom:12px">No brands configured yet — <a href="#" onclick="window.soCloseNewRunModal();window.soOpenBrandForm(\'__new__\');return false" style="color:var(--accent)">add one</a> first.</div>')+
            '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Strategy month</label>'+
            '<input class="form-control" type="month" id="so-new-month" style="margin-bottom:16px">'+
            '<div id="so-new-run-error" style="color:var(--red);font-size:12px;margin-bottom:10px;display:none"></div>'+
            '<div style="display:flex;gap:8px">'+
              '<button class="btn btn-ghost" style="flex:1" onclick="window.soCloseNewRunModal()">Cancel</button>'+
              (brands.length ? '<button class="btn btn-primary" style="flex:1" id="so-new-run-submit" onclick="window.soSubmitNewRun()">Start research</button>' : '')+
            '</div>'+
          '</div>'+
        '</div>';
    }

    // The "front" of the pipeline — the first stage in STAGE_ORDER that isn't approved yet.
    // Once every stage is approved, this returns the last stage (deck-builder) so the UI
    // still has something concrete to point at.
    function currentStageOf(run){
      if(!run || !run.stages) return STAGE_ORDER[0];
      for(var i=0;i<STAGE_ORDER.length;i++){
        var s = STAGE_ORDER[i];
        var st = run.stages[s];
        if(!st || st.status !== "approved") return s;
      }
      return STAGE_ORDER[STAGE_ORDER.length-1];
    }

    function soOpenNewRunModal(){
      soRenderRunList();
      _soNewRunModalOpen = true;
      var modal = document.getElementById("so-new-run-modal");
      var monthInput = document.getElementById("so-new-month");
      if(monthInput && !monthInput.value){
        var d = new Date(); d.setMonth(d.getMonth()+1);
        monthInput.value = d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0");
      }
      if(modal) modal.style.display = "flex";
    }
    function soCloseNewRunModal(){
      _soNewRunModalOpen = false;
      var modal = document.getElementById("so-new-run-modal");
      if(modal) modal.style.display = "none";
    }

    async function soSubmitNewRun(){
      var brandId = document.getElementById("so-new-brand").value;
      var month = document.getElementById("so-new-month").value;
      var errEl = document.getElementById("so-new-run-error");
      var btn = document.getElementById("so-new-run-submit");
      if(errEl){ errEl.style.display="none"; }
      if(!month){ if(errEl){ errEl.textContent="Pick a month."; errEl.style.display="block"; } return; }
      if(btn){ btn.disabled=true; btn.textContent="Starting…"; }
      try {
        var res = await fetch("/.netlify/functions/strategy-run-start", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ brandId: brandId, month: month, actor: currentUser || "Unknown" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not start this run.")+(data.reason?" — "+data.reason:""));
        soCloseNewRunModal();
        window.soOpenRun(data.runId);
      } catch(e) {
        if(errEl){ errEl.textContent = e.message || String(e); errEl.style.display="block"; }
      } finally {
        if(btn){ btn.disabled=false; btn.textContent="Start research"; }
      }
    }

    // Archives a run — mainly for clearing out stale/duplicate test or abandoned runs,
    // which otherwise permanently block starting a fresh one for that brand+month
    // (strategy-run-start.js's own 409 "already an active run" check treats a listed run as
    // live until it's either approved all the way through or archived). Unlike the old
    // outright Delete this used to be, archiving is reversible: the run drops out of the
    // active list and the duplicate-run check, but nothing about it is touched or lost, and
    // it can be restored from the Archived view at any time. Direct Firebase write, same as
    // the per-asset lock toggle — no backend logic needed.
    async function soArchiveRun(runId){
      if(!_db) return;
      var run = (window._soRunsCache || {})[runId];
      var label = run ? (soBrandName(run.brandId)+' · '+monthLabel(run.month)) : runId;
      if(!confirm('Archive this run ('+label+')? It moves to the Archived view and won\'t block starting a new run for the same brand + month. You can restore it anytime.')) return;
      var reason = prompt('Optional: why are you archiving this?') || "";
      await _db.ref("strategy_runs/"+runId).update({
        archivedAt: new Date().toISOString(),
        archivedBy: currentUser || "Unknown",
        archiveReason: reason || null,
      });
    }

    async function soRestoreRun(runId){
      if(!_db) return;
      var run = (window._soRunsCache || {})[runId];
      var label = run ? (soBrandName(run.brandId)+' · '+monthLabel(run.month)) : runId;
      if(!confirm('Restore this run ('+label+')? It reappears in the active list.')) return;
      await _db.ref("strategy_runs/"+runId).update({ archivedAt: null, archivedBy: null, archiveReason: null });
    }

    // The old outright-Delete behavior, kept as a deliberately harder-to-reach exceptional
    // action — only offered from the Archived view, and gated behind typing the run's exact
    // label back rather than a plain confirm(), matching the same pattern Hub already uses
    // for its other irreversible deletes (see deleteMemberPermanently). The run's own
    // history in strategy_stage_versions/strategy_activity is left behind untouched —
    // orphaned but harmless, never referenced by anything once the run itself is gone.
    async function soPurgeRun(runId){
      if(!_db) return;
      var run = (window._soRunsCache || {})[runId];
      var label = run ? (soBrandName(run.brandId)+' · '+monthLabel(run.month)) : runId;
      var typed = prompt('This PERMANENTLY deletes "'+label+'" — it cannot be restored.\n\nType the run\'s label exactly to confirm:\n\n'+label);
      if(typed === null) return;
      if(typed !== label){ alert('Didn\'t match — nothing was deleted.'); return; }
      await _db.ref("strategy_runs/"+runId).remove();
    }

    // ---------- Run detail / stage review ----------

    var _soCurrentRunRaw = null; // same "skip an unchanged snapshot" guard as soListenRuns()

    function soOpenRun(runId){
      _soOpenRunId = runId;
      _soCurrentRunRaw = null;
      if(_soRunListener){ _soRunListener.ref.off("value", _soRunListener.cb); _soRunListener=null; }
      if(!_db) return;
      var ref = _db.ref("strategy_runs/"+runId);
      var cb = function(snap){
        var val = snap.val();
        var raw = JSON.stringify(val);
        if(raw === _soCurrentRunRaw) return;
        _soCurrentRunRaw = raw;
        window._soCurrentRun = val;
        soRenderRunDetail();
      };
      ref.on("value", cb);
      _soRunListener = { ref: ref, cb: cb };
    }

    function soBackToList(){
      _soOpenRunId = null;
      _soCurrentRunRaw = null;
      window._soCurrentRun = null; // strategy-ui.js's decorator reads this global to build
      // the run-detail workspace (Brand memory / Review status sidebars, the stage rail) —
      // leaving it set to whatever run was last open meant coming back to the plain run
      // list still had that stale run's workspace furniture injected on top of it.
      if(_soRunListener){ _soRunListener.ref.off("value", _soRunListener.cb); _soRunListener=null; }
      soRenderRunList();
    }

    function stageStripHtml(run){
      var stages = STAGE_ORDER;
      // id is load-bearing: strategy-ui.js's decorator hides this specific box (it's
      // redundant once its own numbered stage rail is showing) — it used to guess "the
      // element right after the header" instead, which broke the moment nextActionCardHtml
      // started rendering first (see strategy-ui.js's buildWorkspace for the full story).
      return '<div id="so-stage-strip" style="display:flex;gap:8px;margin:14px 0 20px;flex-wrap:wrap">'+
        stages.map(function(s){
          var st = (run.stages && run.stages[s]) || {status:"locked"};
          var isCurrent = currentStageOf(run) === s;
          var color = st.status === "approved" ? "var(--green)" : st.status === "failed" ? "var(--red)" : (isCurrent ? "var(--accent)" : "var(--muted)");
          return '<div style="flex:1;border:1px solid var(--border);border-radius:10px;padding:10px 12px;'+(isCurrent?'background:var(--surface2)':'')+'">'+
            '<div style="font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.03em">'+esc(STAGE_LABELS[s])+'</div>'+
            '<div style="font-weight:700;color:'+color+'">'+esc(statusLabel(st.status))+'</div>'+
          '</div>';
        }).join("")+
      '</div>';
    }

    // Dispatch table from stage key to that stage's review-screen renderer — the detailed
    // boards below the "next action" card. Each renderer takes (run, stage) where stage is
    // run.stages[<key>], same shape as the original two.
    var STAGE_REVIEW_RENDERERS = {
      research: researchReviewHtml,
      strategy: strategyReviewHtml,
      copy: copyReviewHtml,
      "creative-direction": directionReviewHtml,
      "deck-builder": deckReviewHtml,
    };

    // The most-advanced stage that actually has a checkpoint to show — walked from the end
    // of STAGE_ORDER backwards so approving further stages naturally moves the detailed
    // review screen forward without needing separate state.
    function latestReviewableStage(run){
      for(var i=STAGE_ORDER.length-1;i>=0;i--){
        var s = STAGE_ORDER[i];
        var st = run.stages && run.stages[s];
        if(st && st.checkpoint && (st.status==="needs_review"||st.status==="approved"||st.status==="changes_requested")) return s;
      }
      return null;
    }

    function soRenderRunDetail(){
      var root = soRoot(); if(!root) return;
      var run = window._soCurrentRun;
      if(!run){
        root.innerHTML = '<div class="note" style="margin-top:20px">This run could not be found.</div><button class="btn btn-ghost" style="margin-top:12px" onclick="window.soBackToList()">&larr; Back to Strategy OS</button>';
        return;
      }
      var brandName = soBrandName(run.brandId);
      var reviewStage = latestReviewableStage(run);
      var body = reviewStage
        ? STAGE_REVIEW_RENDERERS[reviewStage](run, run.stages[reviewStage])
        : pendingStageHtml(run);

      root.innerHTML =
        '<div class="section-header" style="margin-top:0">'+
          '<div><button class="btn btn-ghost" style="padding:4px 10px;font-size:11px;margin-bottom:8px" onclick="window.soBackToList()">&larr; All runs</button>'+
          '<div class="section-title">'+esc(brandName)+' &middot; '+esc(monthLabel(run.month))+'</div></div>'+
        '</div>'+
        nextActionCardHtml(run)+
        stageStripHtml(run)+
        body;
    }

    // The single "Your next action" card the brief asks for — one place that always says,
    // in plain language, what's happening and what (if anything) there is to do about it
    // right now. This sits above the detailed stage strip/review boards; those stay in
    // place underneath for anyone who wants the full detail, but this card alone should be
    // enough for the common case of "what do I do next".
    // Three bouncing dots, the same shape as a typing indicator — used both for a stage
    // genuinely running/repairing and for a button's own click while its request is still
    // in flight, so nothing that's actually working ever just sits there looking stalled.
    function soWorkingDots(){
      return '<span class="so-working" aria-hidden="true"><span></span><span></span><span></span></span>';
    }

    function nextActionCardHtml(run){
      var stage = currentStageOf(run);
      var st = (run.stages && run.stages[stage]) || {status:"locked"};
      var phrase = plainActionPhrase(stage, st.status);
      var isWorking = st.status === "running" || st.status === "repairing";
      var accent = st.status === "failed" ? "var(--red)" : st.status === "needs_review" ? "var(--accent)" : st.status === "approved" ? "var(--green)" : "var(--text)";

      var actionHtml = "";
      if(st.status === "needs_review"){
        actionHtml =
          '<textarea class="form-control" id="so-decision-notes" placeholder="Notes (optional)" style="margin:10px 0;min-height:56px"></textarea>'+
          '<div id="so-decision-error" style="color:var(--red);font-size:12px;margin-bottom:8px;display:none"></div>'+
          '<div style="display:flex;gap:8px">'+
            '<button class="btn btn-ghost" id="so-decision-notes-btn" style="flex:1" onclick="window.soDecide(\''+esc(run.runId)+'\',\''+esc(stage)+'\',\'changes_requested\')">Send back with notes</button>'+
            '<button class="btn btn-primary" id="so-decision-approve-btn" style="flex:1" onclick="window.soDecide(\''+esc(run.runId)+'\',\''+esc(stage)+'\',\'approved\')">Approve</button>'+
          '</div>';
      } else if(st.status === "failed"){
        actionHtml =
          '<div class="note" style="color:var(--red);margin:8px 0">'+esc(st.detail || "No details recorded.")+'</div>'+
          '<div id="so-retry-error" style="color:var(--red);font-size:12px;margin-bottom:8px;display:none"></div>'+
          '<button class="btn btn-primary" id="so-retry-btn" onclick="window.soRetryStage(\''+esc(run.runId)+'\',\''+esc(stage)+'\')">Retry</button>';
      } else if(st.status === "changes_requested"){
        actionHtml = '<div class="note" style="margin:8px 0">Sent back for changes — this needs a person to update the run and retry '+esc(STAGE_LABELS[stage])+' by hand for now.</div>';
      } else if(isWorking){
        actionHtml = '<div class="note" style="margin:8px 0;display:flex;align-items:center;gap:8px">'+soWorkingDots()+'<span>'+esc(st.detail || "Working…")+' This updates live — no need to refresh.</span></div>';
      } else if(stage === "deck-builder" && st.status === "approved"){
        actionHtml = deckCompleteActionsHtml(run);
      }

      return '<div class="att-board" style="border-color:'+accent+'">'+
        '<div class="bh">Your next action</div>'+
        '<div style="font-size:20px;font-weight:700;color:'+accent+'">'+(isWorking?(STAGE_AGENT_EMOJI[stage]||"🤖")+' ':'')+esc(phrase)+(isWorking?' '+soWorkingDots():'')+'</div>'+
        '<div style="font-size:12px;color:var(--muted);margin-top:2px">'+esc(STAGE_LABELS[stage])+' stage</div>'+
        actionHtml+
      '</div>';
    }

    // Shown once the deck stage is approved — the run's actual "done" state. Canva's own
    // status can still be not_configured/failed even here (deck content itself doesn't
    // depend on Canva succeeding), so this reflects that rather than assuming success.
    function deckCompleteActionsHtml(run){
      var deckStage = run.stages && run.stages["deck-builder"];
      var canva = deckStage && deckStage.canva;
      var tasksCreated = !!run.teamTasksCreatedAt;
      var canvaBtn = "";
      if(canva && canva.status === "published" && canva.url){
        canvaBtn = '<a class="btn btn-primary" style="flex:1;text-align:center;text-decoration:none" href="'+esc(canva.url)+'" target="_blank">Open Canva deck</a>';
      } else if(canva && canva.status === "failed"){
        canvaBtn = '<div class="note" style="color:var(--red);flex:1">Canva publish failed: '+esc(canva.detail||"Unknown error")+'</div>';
      } else {
        canvaBtn = '<div class="note" style="flex:1">'+esc((canva && canva.detail) || "Canva isn't connected for this brand yet — the deck content is ready above.")+'</div>';
      }
      // The .pptx works for every brand regardless of Canva setup — no credentials, no
      // OAuth, generated fresh from the deck's current content on every click. It's a
      // plain link (not a fetch), so the browser's own same-origin cookie handles auth
      // and the response's Content-Disposition just triggers a normal save dialog.
      var downloadBtn = '<a class="btn btn-primary" style="flex:1;text-align:center;text-decoration:none" href="/.netlify/functions/strategy-deck-download?runId='+encodeURIComponent(run.runId)+'">Download deck (.pptx)</a>';
      return '<div style="display:flex;gap:8px;margin-top:10px;align-items:center;flex-wrap:wrap">'+
        downloadBtn+
        canvaBtn+
        '<button class="btn '+(tasksCreated?'btn-ghost':'btn-primary')+'" style="flex:1" id="so-team-tasks-btn" onclick="window.soCreateTeamTasks(\''+esc(run.runId)+'\')" '+(tasksCreated?'disabled':'')+'>'+
          (tasksCreated ? "Team tasks created ✓" : "Create team tasks")+
        '</button>'+
      '</div>';
    }

    function pendingStageHtml(run){
      // The "next action" card above already covers running/failed/changes_requested — this
      // is only reached for a stage still "locked" (waiting on an earlier approval) or
      // "queued" with no checkpoint rendered yet, where there's genuinely nothing more to
      // show than the stage strip already does.
      return '<div class="att-board"><div class="bh">Nothing to review yet</div>'+
        '<div class="note">This run hasn\'t produced anything to review yet — check "Your next action" above.</div></div>';
    }

    async function soRetryStage(runId, stage){
      var errEl = document.getElementById("so-retry-error");
      var btn = document.getElementById("so-retry-btn");
      if(errEl){ errEl.style.display="none"; }
      if(btn){ btn.disabled=true; btn.innerHTML="Retrying… "+soWorkingDots(); }
      try {
        var res = await fetch("/.netlify/functions/strategy-stage-retry", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ runId: runId, stage: stage, actor: currentUser || "Unknown" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not retry this stage.")+(data.reason?" — "+data.reason:""));
        // The live Firebase listener re-renders once the retry's writes land.
      } catch(e) {
        if(errEl){ errEl.textContent = e.message || String(e); errEl.style.display="block"; }
      } finally {
        if(btn){ btn.disabled=false; btn.textContent="Retry"; }
      }
    }

    // "Go back" to an already-approved stage — a real, destructive reset, not a soft undo:
    // see pipeline.js's reopenStage() for the full picture. Every stage after the one
    // being reopened gets wiped back to "locked" (snapshotted first, nothing silently
    // lost), because their content was built against what the reopened stage used to say.
    // Triggered by clicking a completed stage in strategy-ui.js's numbered rail.
    async function soReopenStage(runId, stage){
      var stageIdx = STAGE_ORDER.indexOf(stage);
      var downstream = stageIdx > -1 ? STAGE_ORDER.slice(stageIdx+1).map(function(s){ return STAGE_LABELS[s]; }) : [];
      var warning = "Reopen "+(STAGE_LABELS[stage]||stage)+"? "+
        (downstream.length ? "Everything after it ("+downstream.join(", ")+") will be reset and will need to be regenerated. " : "")+
        "This can't be undone.";
      if(!confirm(warning)) return;
      var notes = prompt("Optional: what needs to change?") || "";
      try {
        var res = await fetch("/.netlify/functions/strategy-stage-reopen", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ runId: runId, stage: stage, notes: notes, actor: currentUser || "Unknown" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not reopen this stage.")+(data.reason?" — "+data.reason:""));
        // The live Firebase listener re-renders once the reset lands.
      } catch(e) {
        alert("Could not reopen: "+(e.message||e));
      }
    }

    // Pushes one Hub task per deck page into the same `tasks` collection the rest of Hub's
    // Task Board already reads (see fbAddTask()) — deliberately NOT calling fbAddTask()
    // itself, since that function's dedup/auto-task machinery (is_auto/AUTO_TASK_KEYS) is
    // built for the recurring brand-of-day tasks, not a one-off fan-out like this. Every
    // page is assigned to the run's owner (Strategy OS doesn't have its own member picker),
    // so whoever ran this can immediately reassign from the Task Board if needed.
    async function soCreateTeamTasks(runId){
      if(!_db) return;
      var btn = document.getElementById("so-team-tasks-btn");
      if(btn){ btn.disabled=true; btn.innerHTML="Creating… "+soWorkingDots(); }
      try {
        // Read the run fresh from Firebase rather than trusting window._soCurrentRun —
        // that cache is only updated by soOpenRun's own listener callback, and reading it
        // here would race against that if a snapshot is still in flight at click time.
        var snap = await _db.ref("strategy_runs/"+runId).once("value");
        var run = snap.val();
        var deckStage = run && run.stages && run.stages["deck-builder"];
        var pages = deckStage && deckStage.checkpoint && deckStage.checkpoint.pages;
        if(!run || !pages || !pages.length) throw new Error("This run has no finished deck to create tasks from.");
        var owner = run.owner || currentUser || "Gokul";
        var brandName = soBrandName(run.brandId);
        pages.forEach(function(p){
          _db.ref("tasks").push({
            member: owner, brand: run.brandId, brands: [run.brandId],
            task: "Produce "+p.format+" — "+p.idea+" ("+brandName+", "+monthLabel(run.month)+")",
            is_personal: false, priority: "Medium", status: "Not Started",
            due_date: "", assigned_by: currentUser || owner, overseers: [],
            created_at: new Date().toISOString(), assigned_on: fmtStamp(new Date()),
            strategy_run_id: run.runId, strategy_asset_id: p.assetId,
          });
        });
        await _db.ref("strategy_runs/"+runId).update({ teamTasksCreatedAt: new Date().toISOString() });
      } catch(e) {
        if(btn){ btn.disabled=false; btn.textContent="Create team tasks"; }
        alert("Could not create team tasks: "+(e.message||e));
        return;
      }
      if(btn){ btn.disabled=false; }
    }

    function researchReviewHtml(run, stage){
      var r = stage.checkpoint;
      var readOnly = stage.status === "approved";
      var qRows = (r.liveQuestions||[]).map(function(q){
        var srcs = q.sourceIds.map(function(id){ var s=(r.sources||[]).find(function(x){return x.id===id;}); return s ? '<a href="'+esc(s.url)+'" target="_blank" style="color:var(--accent)">'+esc(s.type)+'</a>' : id; }).join(", ");
        return '<div class="pf-absrow" style="align-items:flex-start;flex-direction:column;gap:4px;border-bottom:1px solid var(--border);padding:10px 0">'+
          '<div style="font-weight:600">&ldquo;'+esc(q.verbatim)+'&rdquo;</div>'+
          '<div style="font-size:12px;color:var(--muted)">'+esc(q.underlyingNeed)+'</div>'+
          '<div style="font-size:11px">Source: '+srcs+'</div>'+
        '</div>';
      }).join("");

      var argRows = (r.arguments||[]).map(function(a){
        return '<div style="border-bottom:1px solid var(--border);padding:10px 0">'+
          '<div style="font-weight:600">'+esc(a.disagreement)+'</div>'+
          '<div style="font-size:12px;margin-top:4px"><b>Side A:</b> '+esc(a.sideA)+'</div>'+
          '<div style="font-size:12px"><b>Side B:</b> '+esc(a.sideB)+'</div>'+
          '<div style="font-size:12px;color:var(--accent);margin-top:4px">Credible position: '+esc(a.credibleBrandPosition)+' — '+esc(a.credibilityReason)+'</div>'+
        '</div>';
      }).join("");

      var behRows = (r.unspokenBehaviours||[]).map(function(b){
        return '<div style="border-bottom:1px solid var(--border);padding:10px 0">'+
          '<div style="font-weight:600">'+esc(b.behaviour)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)">'+esc(b.hiddenTension)+'</div>'+
        '</div>';
      }).join("");

      var killRows = (r.exhaustedTerritory||[]).map(function(t){
        return '<div style="border-bottom:1px solid var(--border);padding:8px 0"><b>'+esc(t.territory)+'</b> — '+esc(t.reasonExhausted)+'</div>';
      }).join("");

      return '<div class="att-board"><div class="bh">Live questions <span class="tag">'+(r.liveQuestions||[]).length+'</span></div>'+qRows+'</div>'+
        '<div class="att-board"><div class="bh">Category arguments <span class="tag">'+(r.arguments||[]).length+'</span></div>'+argRows+'</div>'+
        '<div class="att-board"><div class="bh">Unspoken behaviours <span class="tag">'+(r.unspokenBehaviours||[]).length+'</span></div>'+behRows+'</div>'+
        '<div class="att-board"><div class="bh">Exhausted territory (kill list) <span class="tag">'+(r.exhaustedTerritory||[]).length+'</span></div>'+killRows+'</div>'+
        (readOnly
          ? '<div class="note">Research approved '+esc(fmtDateTime((run.approvals&&run.approvals.research&&run.approvals.research.decidedAt)))+' by '+esc(run.approvals&&run.approvals.research&&run.approvals.research.decidedBy)+'.</div>'
          // Approve/Send back with notes live in the "Your next action" card above, not
          // duplicated here — this avoided two independent controls (and two elements
          // sharing the same #so-decision-notes id) doing the same thing on one page.
          : '<div class="note">Use the "Your next action" card above to approve this or send it back with notes.</div>');
    }

    function gateChip(pass, label){
      return '<span style="display:inline-block;margin:2px 6px 2px 0;padding:2px 9px;border-radius:6px;font-size:10.5px;font-weight:700;'+
        (pass ? 'background:#12291d;border:1px solid #2a5a3a;color:var(--green)' : 'background:#2c1414;border:1px solid #5a2a2a;color:var(--red)')+'">'+
        (pass?'✓ ':'✗ ')+esc(label)+'</span>';
    }

    // The proposed-replacement block shown under a concept once a refine/similar/discard
    // request is in flight or done — reads stage.candidates[assetId] (see pipeline.js's
    // proposeConceptCandidate/acceptConceptCandidate). Discard candidates never render here
    // as "ready" — they auto-accept, so by the time the UI sees them they're either still
    // "running" or already gone (committed straight into the checkpoint).
    // Preview shown for a "ready" candidate differs by stage — StrategyAssetSchema has
    // conceptName/tension, CopyAssetSchema has captions/claimAudit instead — everything
    // else about proposing/accepting/rejecting it is identical across stages.
    function conceptCandidateHtml(runId, stage, assetId, candidate){
      if(!candidate) return "";
      if(candidate.status === "running"){
        return '<div class="note" style="margin-top:8px;display:flex;align-items:center;gap:8px">'+soWorkingDots()+'<span>'+esc(candidate.detail || "Working on a replacement…")+'</span></div>';
      }
      if(candidate.status === "failed"){
        return '<div class="note" style="margin-top:8px;color:var(--red)">Couldn\'t generate a replacement: '+esc(candidate.detail||"Unknown error")+'</div>'+
          '<button class="btn btn-ghost" style="margin-top:6px;font-size:11px;padding:4px 10px" onclick="window.soRetryConceptCandidate(\''+esc(runId)+'\',\''+esc(stage)+'\',\''+esc(assetId)+'\')">Try again</button>';
      }
      if(candidate.status === "ready" && candidate.candidate){
        var c = candidate.candidate;
        var preview = stage === "copy"
          ? '<div style="margin:4px 0;font-style:italic">&ldquo;'+esc(c.hook)+'&rdquo;</div>'+
            '<div style="font-size:12px;color:var(--muted)">'+esc((c.captions&&c.captions[0]&&c.captions[0].copy)||'')+'</div>'+
            '<div style="margin-top:4px">'+claimStatusChip(c.claimAudit&&c.claimAudit.status)+'</div>'
          : '<div style="font-weight:700">'+esc(c.conceptName)+'</div>'+
            '<div style="margin:4px 0;font-style:italic">&ldquo;'+esc(c.hook)+'&rdquo;</div>'+
            '<div style="font-size:12px;color:var(--muted)"><b>Tension:</b> '+esc(c.tension)+'</div>';
        return '<div style="margin-top:8px;border:1px solid var(--accent);border-radius:10px;padding:12px;background:var(--surface2)">'+
          '<div style="font-size:10px;color:var(--accent);text-transform:uppercase;letter-spacing:.04em;font-weight:700;margin-bottom:6px">Proposed replacement</div>'+
          preview+
          '<div style="display:flex;gap:8px;margin-top:8px">'+
            '<button class="btn btn-ghost" style="flex:1" onclick="window.soRejectConceptCandidate(\''+esc(runId)+'\',\''+esc(stage)+'\',\''+esc(assetId)+'\')">Discard suggestion</button>'+
            '<button class="btn btn-primary" style="flex:1" onclick="window.soAcceptConceptCandidate(\''+esc(runId)+'\',\''+esc(stage)+'\',\''+esc(assetId)+'\')">Use this instead</button>'+
          '</div>'+
        '</div>';
      }
      return "";
    }

    function strategyReviewHtml(run, stage){
      var stageKey = "strategy";
      var s = stage.checkpoint;
      var readOnly = stage.status === "approved";
      var candidates = stage.candidates || {};
      var locks = stage.locks || {};
      var byFormat = (s.assets||[]).reduce(function(acc,a){ acc[a.format]=(acc[a.format]||0)+1; return acc; }, {});
      var assetRows = (s.assets||[]).map(function(a){
        var candidate = candidates[a.assetId];
        var busy = candidate && candidate.status === "running";
        var locked = !!locks[a.assetId];
        var actionsHtml = readOnly ? "" :
          '<div style="margin-top:10px;display:flex;gap:6px;flex-wrap:wrap">'+
            '<button class="btn btn-ghost" style="font-size:11px;padding:4px 10px" '+(busy?'disabled':'')+' onclick="window.soToggleRefineBox(\''+esc(stageKey)+'\',\''+esc(a.assetId)+'\')">Refine</button>'+
            '<button class="btn btn-ghost" style="font-size:11px;padding:4px 10px" '+(busy?'disabled':'')+' onclick="window.soSuggestSimilar(\''+esc(run.runId)+'\',\''+esc(a.assetId)+'\')">Suggest similar</button>'+
            '<button class="btn btn-ghost" style="font-size:11px;padding:4px 10px;color:var(--red);border-color:var(--red)" '+(busy?'disabled':'')+' onclick="window.soDiscardConcept(\''+esc(run.runId)+'\',\''+esc(a.assetId)+'\')">Discard</button>'+
            '<button class="btn '+(locked?'btn-primary':'btn-ghost')+'" style="font-size:11px;padding:4px 10px;margin-left:auto" onclick="window.soToggleAssetLock(\''+esc(run.runId)+'\',\''+esc(stageKey)+'\',\''+esc(a.assetId)+'\','+locked+')">'+(locked?'🔒 Locked':'Lock')+'</button>'+
          '</div>'+
          '<div id="so-refine-box-'+esc(stageKey)+'-'+esc(a.assetId)+'" style="display:none;margin-top:8px">'+
            '<textarea class="form-control" id="so-refine-notes-'+esc(stageKey)+'-'+esc(a.assetId)+'" placeholder="What should change about this concept?" style="min-height:50px;font-size:12px;margin-bottom:6px"></textarea>'+
            '<button class="btn btn-primary" style="font-size:11px;padding:4px 12px" onclick="window.soSendRefine(\''+esc(run.runId)+'\',\''+esc(stageKey)+'\',\''+esc(a.assetId)+'\')">Send</button>'+
          '</div>';
        return '<div style="border-bottom:1px solid var(--border);padding:12px 0'+(locked?';opacity:.85':'')+'">'+
          '<div style="display:flex;justify-content:space-between;align-items:baseline;gap:10px">'+
            '<div style="font-weight:700">'+esc(a.assetId)+' &middot; '+esc(a.format)+' &middot; '+esc(a.conceptName)+(locked?' <span style="color:var(--green);font-size:11px">🔒</span>':'')+'</div>'+
            '<div style="font-size:11px;color:var(--muted)">'+esc(a.portfolioId||'—')+'</div>'+
          '</div>'+
          '<div style="margin:6px 0;font-style:italic">&ldquo;'+esc(a.hook)+'&rdquo;</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Tension:</b> '+esc(a.tension)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Send to:</b> '+esc(a.sendTo)+'</div>'+
          '<div style="margin-top:8px">'+
            gateChip(a.gate.logoSwapPass,"Logo-swap")+gateChip(a.gate.killListPass,"Kill list")+
            gateChip(a.gate.tensionPass,"Tension")+gateChip(a.gate.overheardPass,"Overheard")+
          '</div>'+
          actionsHtml+
          conceptCandidateHtml(run.runId, stageKey, a.assetId, candidate)+
        '</div>';
      }).join("");

      return '<div class="att-board">'+
          '<div class="bh">Asset plan <span class="tag">'+(s.assets||[]).length+' assets</span></div>'+
          '<div style="font-size:12px;color:var(--muted);margin-bottom:10px">'+
            (byFormat.reel||0)+' reel &middot; '+(byFormat.carousel||0)+' carousel &middot; '+(byFormat.static||0)+' static'+
          '</div>'+
          '<div style="font-size:13px;margin-bottom:10px"><b>Month thesis:</b> '+esc(s.monthThesis)+'</div>'+
        '</div>'+
        '<div class="att-board"><div class="bh" style="display:flex;align-items:center;justify-content:space-between;gap:10px">Concepts'+(readOnly?'':assetLockSummaryHtml(locks, (s.assets||[]).length))+'</div>'+assetRows+'</div>'+
        (s.discarded && s.discarded.length ? '<div class="att-board"><div class="bh">Discarded candidates <span class="tag">'+s.discarded.length+'</span></div>'+
          s.discarded.map(function(d){ return '<div style="border-bottom:1px solid var(--border);padding:8px 0"><b>'+esc(d.conceptName)+'</b> — failed '+esc(d.failedGate)+': '+esc(d.reason)+'</div>'; }).join("")+
        '</div>' : '')+
        (readOnly
          ? '<div class="note">Strategy approved '+esc(fmtDateTime((run.approvals&&run.approvals.strategy&&run.approvals.strategy.decidedAt)))+' by '+esc(run.approvals&&run.approvals.strategy&&run.approvals.strategy.decidedBy)+'.</div>'
          : '<div class="note">Use the "Your next action" card above to approve this or send it back with notes.</div>');
    }

    function claimStatusChip(status){
      var color = status === "ready" ? "var(--green)" : status === "flagged" ? "#e0a53a" : "var(--red)";
      var bg = status === "ready" ? "#12291d" : status === "flagged" ? "#3a2c12" : "#2c1414";
      return '<span style="display:inline-block;padding:2px 9px;border-radius:6px;font-size:10.5px;font-weight:700;background:'+bg+';color:'+color+'">'+esc(status||'—')+'</span>';
    }

    function copyReviewHtml(run, stage){
      var stageKey = "copy";
      var c = stage.checkpoint;
      var readOnly = stage.status === "approved";
      var candidates = stage.candidates || {};
      var locks = stage.locks || {};
      var assetRows = (c.assets||[]).map(function(a){
        var frames = (a.onCreative && a.onCreative.frames || []).map(function(f){ return '<div style="font-size:12px;color:var(--muted)">'+esc(f.label)+': '+esc(f.text)+'</div>'; }).join("");
        var script = (a.script && a.script.scenes && a.script.scenes.length)
          ? '<div style="margin-top:8px"><b style="font-size:12px">Script ('+a.script.durationSeconds+'s)</b>'+
            a.script.scenes.map(function(sc){ return '<div style="font-size:12px;color:var(--muted);margin-top:4px">'+esc(sc.timing)+' — '+esc(sc.visual)+' &middot; VO: "'+esc(sc.voiceover)+'"</div>'; }).join("")+
            '</div>'
          : "";
        var captions = (a.captions||[]).map(function(cap){
          return '<div style="border-top:1px solid var(--border);padding-top:6px;margin-top:6px">'+
            '<div style="font-size:11px;color:var(--muted);text-transform:uppercase">Version '+esc(cap.version)+' &middot; '+esc(cap.angle)+'</div>'+
            '<div style="font-size:13px;white-space:pre-wrap">'+esc(cap.copy)+'</div>'+
            '<div style="font-size:11px;color:var(--accent)">'+(cap.hashtags||[]).map(function(h){return esc(h);}).join(' ')+'</div>'+
          '</div>';
        }).join("");
        var audit = a.claimAudit || {};
        var candidate = candidates[a.assetId];
        var busy = candidate && candidate.status === "running";
        var locked = !!locks[a.assetId];
        var actionsHtml = readOnly ? "" :
          '<div style="margin-top:10px;display:flex;gap:6px;flex-wrap:wrap">'+
            '<button class="btn btn-ghost" style="font-size:11px;padding:4px 10px" '+(busy?'disabled':'')+' onclick="window.soToggleRefineBox(\''+esc(stageKey)+'\',\''+esc(a.assetId)+'\')">Refine</button>'+
            '<button class="btn btn-ghost" style="font-size:11px;padding:4px 10px;color:var(--red);border-color:var(--red)" '+(busy?'disabled':'')+' onclick="window.soReplaceCopyAsset(\''+esc(run.runId)+'\',\''+esc(a.assetId)+'\')">Replace</button>'+
            '<button class="btn '+(locked?'btn-primary':'btn-ghost')+'" style="font-size:11px;padding:4px 10px;margin-left:auto" onclick="window.soToggleAssetLock(\''+esc(run.runId)+'\',\''+esc(stageKey)+'\',\''+esc(a.assetId)+'\','+locked+')">'+(locked?'🔒 Locked':'Lock')+'</button>'+
          '</div>'+
          '<div id="so-refine-box-'+esc(stageKey)+'-'+esc(a.assetId)+'" style="display:none;margin-top:8px">'+
            '<textarea class="form-control" id="so-refine-notes-'+esc(stageKey)+'-'+esc(a.assetId)+'" placeholder="What should change about this copy?" style="min-height:50px;font-size:12px;margin-bottom:6px"></textarea>'+
            '<button class="btn btn-primary" style="font-size:11px;padding:4px 12px" onclick="window.soSendRefine(\''+esc(run.runId)+'\',\''+esc(stageKey)+'\',\''+esc(a.assetId)+'\')">Send</button>'+
          '</div>';
        return '<div style="border-bottom:1px solid var(--border);padding:12px 0'+(locked?';opacity:.85':'')+'">'+
          '<div style="display:flex;justify-content:space-between;align-items:baseline;gap:10px">'+
            '<div style="font-weight:700">'+esc(a.assetId)+' &middot; '+esc(a.format)+' &middot; '+esc(a.skuNames&&a.skuNames.join(', ')||a.portfolioName||'—')+(locked?' <span style="color:var(--green);font-size:11px">🔒</span>':'')+'</div>'+
            claimStatusChip(audit.status)+
          '</div>'+
          '<div style="margin:6px 0;font-style:italic">&ldquo;'+esc(a.hook)+'&rdquo;</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Cover:</b> '+esc(a.onCreative&&a.onCreative.cover)+'</div>'+
          frames+
          (a.onCreative && a.onCreative.endFrame ? '<div style="font-size:12px;color:var(--muted)"><b>End frame:</b> '+esc(a.onCreative.endFrame)+'</div>' : '')+
          script+
          (audit.rewrittenClaims && audit.rewrittenClaims.length ? '<div style="font-size:12px;color:#e0a53a;margin-top:6px"><b>Rewritten claims:</b> '+audit.rewrittenClaims.map(function(x){return esc(x);}).join('; ')+'</div>' : '')+
          (audit.verificationFlags && audit.verificationFlags.length ? '<div style="font-size:12px;color:var(--red);margin-top:4px"><b>Needs verification:</b> '+audit.verificationFlags.map(function(x){return esc(x);}).join('; ')+'</div>' : '')+
          captions+
          actionsHtml+
          conceptCandidateHtml(run.runId, stageKey, a.assetId, candidate)+
        '</div>';
      }).join("");

      return '<div class="att-board"><div class="bh" style="display:flex;align-items:center;justify-content:space-between;gap:10px"><span>Copy <span class="tag">'+(c.assets||[]).length+' assets</span></span>'+(readOnly?'':assetLockSummaryHtml(locks, (c.assets||[]).length))+'</div>'+assetRows+'</div>'+
        (c.globalVerificationFlags && c.globalVerificationFlags.length ? '<div class="att-board"><div class="bh" style="color:var(--red)">Flags across the whole batch</div>'+
          c.globalVerificationFlags.map(function(f){ return '<div style="padding:6px 0">'+esc(f)+'</div>'; }).join("")+'</div>' : '')+
        (readOnly
          ? '<div class="note">Copy approved '+esc(fmtDateTime((run.approvals&&run.approvals.copy&&run.approvals.copy.decidedAt)))+' by '+esc(run.approvals&&run.approvals.copy&&run.approvals.copy.decidedBy)+'.</div>'
          : '<div class="note">Use the "Your next action" card above to approve this or send it back with notes.</div>');
    }

    function directionReviewHtml(run, stage){
      var d = stage.checkpoint;
      var readOnly = stage.status === "approved";
      var assetRows = (d.assets||[]).map(function(a){
        var shots = (a.shotList||[]).map(function(s){
          return '<div style="font-size:12px;color:var(--muted);border-top:1px solid var(--border);padding-top:6px;margin-top:6px">'+
            '<b>'+esc(s.shot)+':</b> '+esc(s.framing)+' — '+esc(s.action)+' &middot; '+esc(s.productVisibility)+
          '</div>';
        }).join("");
        var refs = (a.references||[]).map(function(r){
          return '<div style="font-size:12px;border-top:1px solid var(--border);padding-top:6px;margin-top:6px">'+
            '<a href="'+esc(r.url)+'" target="_blank" style="color:var(--accent)">'+esc(r.title||r.url)+'</a>'+
            ' &middot; <span style="color:var(--muted)">'+esc(r.source)+'</span>'+
            '<div style="color:var(--muted)">Use for: '+esc(r.useFor)+'</div>'+
            '<div style="color:#e0a53a">'+esc(r.rightsNote)+'</div>'+
          '</div>';
        }).join("");
        return '<div style="border-bottom:1px solid var(--border);padding:12px 0">'+
          '<div style="font-weight:700">'+esc(a.assetId)+' &middot; '+esc(a.format)+' &middot; '+esc(a.productionMode)+'</div>'+
          '<div style="margin:6px 0">'+esc(a.visualConcept)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Art direction:</b> '+esc(a.artDirection)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Palette:</b> '+(a.palette||[]).map(function(p){return esc(p);}).join(', ')+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Typography:</b> '+esc(a.typography)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Composition:</b> '+esc(a.composition)+'</div>'+
          shots+refs+
          (a.designNotes && a.designNotes.length ? '<div style="font-size:12px;margin-top:6px"><b>Design notes:</b> '+a.designNotes.map(function(x){return esc(x);}).join('; ')+'</div>' : '')+
          (a.avoid && a.avoid.length ? '<div style="font-size:12px;color:var(--red)"><b>Avoid:</b> '+a.avoid.map(function(x){return esc(x);}).join('; ')+'</div>' : '')+
        '</div>';
      }).join("");

      return '<div class="att-board"><div class="bh">Creative direction <span class="tag">'+(d.assets||[]).length+' assets</span></div>'+assetRows+'</div>'+
        (d.productionNotes && d.productionNotes.length ? '<div class="att-board"><div class="bh">Production notes</div>'+
          d.productionNotes.map(function(n){ return '<div style="padding:6px 0">'+esc(n)+'</div>'; }).join("")+'</div>' : '')+
        (readOnly
          ? '<div class="note">Creative direction approved '+esc(fmtDateTime((run.approvals&&run.approvals["creative-direction"]&&run.approvals["creative-direction"].decidedAt)))+' by '+esc(run.approvals&&run.approvals["creative-direction"]&&run.approvals["creative-direction"].decidedBy)+'.</div>'
          : '<div class="note">Use the "Your next action" card above to approve this or send it back with notes.</div>');
    }

    var PRODUCTION_STATUSES = ["not_started","in_progress","ready_for_review","complete"];
    var PRODUCTION_STATUS_LABELS = { not_started: "Not started", in_progress: "In progress", ready_for_review: "Ready for review", complete: "Complete" };

    function deckReviewHtml(run, stage){
      var d = stage.checkpoint;
      var readOnly = stage.status === "approved";
      var pageRows = (d.pages||[]).map(function(p, idx){
        return '<div style="border-bottom:1px solid var(--border);padding:12px 0">'+
          '<div style="display:flex;justify-content:space-between;align-items:baseline;gap:10px">'+
            '<div style="font-weight:700">Page '+p.pageNumber+' &middot; '+esc(p.assetId)+' &middot; '+esc(p.format)+'</div>'+
            '<div style="font-size:11px;color:var(--muted)">'+esc(p.portfolioAndSku)+'</div>'+
          '</div>'+
          '<div style="margin:6px 0;font-style:italic">&ldquo;'+esc(p.idea)+'&rdquo;</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Hook:</b> '+esc(p.hook)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Creative copy:</b> '+esc(p.creativeCopy)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Direction:</b> '+esc(p.direction)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Shot list:</b> '+esc(p.shotList)+'</div>'+
          '<div style="font-size:12px;color:var(--muted)"><b>Captions:</b> '+esc(p.captionOne)+' / '+esc(p.captionTwo)+' / '+esc(p.captionThree)+'</div>'+
          (p.referenceImageUrl ? '<div style="font-size:12px"><a href="'+esc(p.referenceImageUrl)+'" target="_blank" style="color:var(--accent)">Reference image</a> &middot; '+esc(p.referenceCredit||'')+'</div>' : '')+
          '<div style="display:flex;gap:8px;margin-top:8px;align-items:center">'+
            '<input class="form-control" style="flex:1;font-size:12px" placeholder="Owner" value="'+esc(p.owner||'')+'" onchange="window.soUpdateDeckPage(\''+esc(run.runId)+'\','+idx+',\'owner\',this.value)">'+
            '<select class="form-control" style="width:170px;font-size:12px" onchange="window.soUpdateDeckPage(\''+esc(run.runId)+'\','+idx+',\'productionStatus\',this.value)">'+
              PRODUCTION_STATUSES.map(function(s){ return '<option value="'+s+'"'+(p.productionStatus===s?' selected':'')+'>'+esc(PRODUCTION_STATUS_LABELS[s])+'</option>'; }).join("")+
            '</select>'+
          '</div>'+
        '</div>';
      }).join("");

      return '<div class="att-board"><div class="bh">'+esc(d.title||'Deck')+' <span class="tag">'+(d.pages||[]).length+' pages</span></div>'+
          (d.subtitle ? '<div style="font-size:12px;color:var(--muted);margin-bottom:10px">'+esc(d.subtitle)+'</div>' : '')+
        '</div>'+
        '<div class="att-board"><div class="bh">Pages</div>'+pageRows+'</div>'+
        (readOnly
          // The Open Canva deck / Create team tasks actions live in the "Your next action"
          // card once the deck is approved (nextActionCardHtml) — not duplicated here.
          ? '<div class="note">Deck approved '+esc(fmtDateTime((run.approvals&&run.approvals["deck-builder"]&&run.approvals["deck-builder"].decidedAt)))+' by '+esc(run.approvals&&run.approvals["deck-builder"]&&run.approvals["deck-builder"].decidedBy)+'.</div>'
          : '<div class="note">Use the "Your next action" card above to approve this or send it back with notes.</div>');
    }

    async function soUpdateDeckPage(runId, pageIndex, field, value){
      if(!_db) return;
      var patch = {}; patch[field] = value;
      await _db.ref("strategy_runs/"+runId+"/stages/deck-builder/checkpoint/pages/"+pageIndex).update(patch);
    }

    // ---------- Per-asset refine / suggest-similar / discard-or-replace ----------
    // See strategy-concept-propose.js / strategy-concept-accept.js / strategy-concept-
    // discard.js — all stage-aware now (pass `stage`). Refine/similar propose a candidate
    // and wait for a person to accept it; each stage's own "kill it, no review" type
    // (strategy's "discard", copy's "replace") auto-accepts — see pipeline.js's
    // replaceAsset(). Strategy is the default `stage` throughout so nothing here needs to
    // change shape for the one stage this shipped on first.

    async function soProposeConcept(runId, stage, assetId, action, notes){
      try {
        var res = await fetch("/.netlify/functions/strategy-concept-propose", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ runId: runId, stage: stage, assetId: assetId, action: action, notes: notes || "" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not start.")+(data.reason?" — "+data.reason:""));
        // The live Firebase listener re-renders once the candidate's status updates.
      } catch(e) {
        alert("Could not generate a replacement: "+(e.message||e));
      }
    }

    function soSuggestSimilar(runId, assetId){
      return soProposeConcept(runId, "strategy", assetId, "similar");
    }

    function soToggleRefineBox(stage, assetId){
      var box = document.getElementById("so-refine-box-"+stage+"-"+assetId);
      if(box) box.style.display = (box.style.display === "none" || !box.style.display) ? "block" : "none";
    }

    function soSendRefine(runId, stage, assetId){
      var notesEl = document.getElementById("so-refine-notes-"+stage+"-"+assetId);
      var notes = notesEl ? notesEl.value.trim() : "";
      if(!notes){ alert("Add a note on what should change first."); return; }
      return soProposeConcept(runId, stage, assetId, "refine", notes);
    }

    async function soDiscardConceptRequest(runId, stage, assetId, notes){
      try {
        var res = await fetch("/.netlify/functions/strategy-concept-discard", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ runId: runId, stage: stage, assetId: assetId, notes: notes || "", actor: currentUser || "Unknown" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not replace this asset.")+(data.reason?" — "+data.reason:""));
      } catch(e) {
        alert("Could not replace: "+(e.message||e));
      }
    }

    async function soDiscardConcept(runId, assetId){
      if(!confirm("Discard this concept? A replacement will be generated automatically.")) return;
      var notes = prompt("Optional: why is this concept being discarded? Helps future strategy avoid the same idea.") || "";
      return soDiscardConceptRequest(runId, "strategy", assetId, notes);
    }

    async function soReplaceCopyAsset(runId, assetId){
      if(!confirm("Replace this asset's copy? A fresh version will be generated automatically.")) return;
      var notes = prompt("Optional: what's wrong with the current copy? Helps the rewrite avoid the same issue.") || "";
      return soDiscardConceptRequest(runId, "copy", assetId, notes);
    }

    async function soAcceptConceptCandidate(runId, stage, assetId){
      try {
        var res = await fetch("/.netlify/functions/strategy-concept-accept", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ runId: runId, stage: stage, assetId: assetId, actor: currentUser || "Unknown" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not accept this candidate.")+(data.reason?" — "+data.reason:""));
      } catch(e) {
        alert("Could not accept: "+(e.message||e));
      }
    }

    // "Discard suggestion" on a ready candidate — just clears it, same direct-write
    // pattern as soUpdateDeckPage. No endpoint needed: nothing's been committed yet.
    async function soRejectConceptCandidate(runId, stage, assetId){
      if(!_db) return;
      await _db.ref("strategy_runs/"+runId+"/stages/"+stage+"/candidates/"+assetId).remove();
    }

    // Re-runs whatever action produced a failed candidate, with the same notes — routed to
    // the right endpoint since a stage's auto-accept type ("discard"/"replace") isn't a
    // valid strategy-concept-propose action.
    function soRetryConceptCandidate(runId, stage, assetId){
      var run = window._soCurrentRun;
      var candidate = run && run.stages && run.stages[stage] && run.stages[stage].candidates && run.stages[stage].candidates[assetId];
      if(!candidate) return;
      if(candidate.requestType === "discard" || candidate.requestType === "replace") return soDiscardConceptRequest(runId, stage, assetId, candidate.notes);
      return soProposeConcept(runId, stage, assetId, candidate.requestType, candidate.notes);
    }

    // ---------- Per-asset lock ----------
    // A lock is purely a human checkpoint — "I've looked at this one, it's good" — with no
    // effect on the stage's own Approve/Send back flow (that stays a separate, independent
    // action either way). No endpoint needed: it's a plain boolean, same direct-write
    // pattern as soRejectConceptCandidate. Using Refine/Replace/Suggest-similar on a locked
    // asset clears its lock server-side the moment the request is sent (see pipeline.js's
    // proposeAssetCandidate) — that's the one thing that silently unlocks it here.
    async function soToggleAssetLock(runId, stage, assetId, currentlyLocked){
      if(!_db) return;
      var ref = _db.ref("strategy_runs/"+runId+"/stages/"+stage+"/locks/"+assetId);
      if(currentlyLocked) await ref.remove();
      else await ref.set({ lockedAt: new Date().toISOString(), lockedBy: currentUser || "Unknown" });
    }

    // "3 of 13 locked · 10 left" — shown at the top of a stage's asset list so reviewing
    // one at a time has a visible finish line, even though locking doesn't gate anything.
    function assetLockSummaryHtml(locks, total){
      var lockedCount = Object.keys(locks || {}).length;
      var left = Math.max(0, total - lockedCount);
      return '<span style="font-size:11px;font-weight:700;padding:3px 10px;border-radius:999px;background:var(--surface2);border:1px solid var(--border);color:'+(lockedCount===total&&total>0?'var(--green)':'var(--muted)')+'">'+
        lockedCount+' of '+total+' locked'+(left>0?' &middot; '+left+' left':'')+
      '</span>';
    }

    async function soDecide(runId, stage, decision){
      var notesEl = document.getElementById("so-decision-notes");
      var errEl = document.getElementById("so-decision-error");
      var approveBtn = document.getElementById("so-decision-approve-btn");
      var notesBtn = document.getElementById("so-decision-notes-btn");
      var clickedBtn = decision === "approved" ? approveBtn : notesBtn;
      if(errEl){ errEl.style.display="none"; }
      // Disable BOTH buttons (not just the one clicked) so a second click can't fire a
      // duplicate decision while the first is still in flight, and show the clicked one
      // as visibly working rather than leaving the whole card looking unresponsive.
      [approveBtn, notesBtn].forEach(function(b){ if(b) b.disabled = true; });
      if(clickedBtn) clickedBtn.innerHTML = (decision === "approved" ? "Approving… " : "Sending… ") + soWorkingDots();
      try {
        var res = await fetch("/.netlify/functions/strategy-stage-approve", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ runId: runId, stage: stage, decision: decision, actor: currentUser || "Unknown", notes: notesEl ? notesEl.value.trim() : "" }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok) throw new Error((data.error||"Could not record this decision.")+(data.reason?" — "+data.reason:""));
        // The live Firebase listener (soOpenRun's cb) re-renders automatically once the
        // function's writes land — no manual re-render needed here (which also replaces
        // these buttons, so there's nothing to re-enable on the success path).
      } catch(e) {
        if(errEl){ errEl.textContent = e.message || String(e); errEl.style.display="block"; }
        [approveBtn, notesBtn].forEach(function(b){ if(b) b.disabled = false; });
        if(approveBtn) approveBtn.textContent = "Approve";
        if(notesBtn) notesBtn.textContent = "Send back with notes";
      }
    }

    // ---------- Manage brands (brief section 13: brand config as a form, not raw JSON) ----------
    // Common fields (basics, voice, audience, visual, deliverables, pillars) get real form
    // controls. Portfolios/claim rules/copy structure/Canva config are collapsed under
    // "Advanced" as a raw-JSON editor rather than full nested sub-forms for every product
    // and claim rule — most brands won't need them (RRO is the one that does), and building
    // a repeatable-array-of-object editor three levels deep for a field almost nothing else
    // uses isn't worth it yet. The server validates the merged whole either way.

    function soOpenBrandList(){
      _soBrandView = "list";
      soRenderBrandList();
    }

    function soBackToRunsFromBrands(){
      _soBrandView = null;
      soRenderRunList();
    }

    function soRenderBrandList(){
      var root = soRoot(); if(!root) return;
      var brands = soBrandList();
      var rows = brands.map(function(b){
        return '<div class="pf-absrow" style="border-bottom:1px solid var(--border);padding:10px 0">'+
          '<div><b>'+esc(b.name)+'</b><div style="font-size:11px;color:var(--muted)">'+esc(b.category||'—')+' · '+esc(b.id)+'</div></div>'+
          '<button class="btn btn-ghost" style="padding:4px 12px;font-size:11px" onclick="window.soOpenBrandForm(\''+esc(b.id)+'\')">Edit</button>'+
        '</div>';
      }).join("");
      root.innerHTML =
        '<div class="section-header" style="margin-top:0">'+
          '<div><button class="btn btn-ghost" style="padding:4px 10px;font-size:11px;margin-bottom:8px" onclick="window.soBackToRunsFromBrands()">&larr; All runs</button>'+
          '<div class="section-title">Manage brands</div></div>'+
          '<button class="btn btn-primary" onclick="window.soOpenBrandForm(\'__new__\')">+ Add brand</button>'+
        '</div>'+
        '<div class="att-board"><div class="bh">Brands<span class="tag">'+brands.length+'</span></div>'+
          (brands.length ? rows : '<div class="note">No brands configured yet — add the first one.</div>')+
        '</div>';
    }

    function soDefaultBrandTemplate(id){
      return {
        schemaVersion: "1.0", id: id || "", name: "", category: "",
        market: [], aspirationalMarkets: [], website: null, driveFolderUrl: null, oneLineTruth: "",
        deliverables: { reel: 6, carousel: 4, static: 3, confirmed: false },
        voice: { descriptors: [], principles: [], bannedWords: [], bannedMoves: [], emojiRule: "", languageRule: "" },
        audiences: [],
        visual: { feel: [], palette: [], principles: [], avoid: [] },
        pillars: [],
        competitors: [], portfolios: [], claimRules: [], copyStructure: null,
        knownUnknowns: [], sourceVectorStoreIds: [],
        canva: {
          enabled: false, mode: "brand_template",
          templateIdEnv: "CANVA_BRAND_TEMPLATE_ID", sourceDesignIdEnv: "CANVA_SOURCE_DESIGN_ID",
          fieldPrefix: "ASSET", indexWidth: 2,
          fields: { format: "FORMAT", portfolio: "PORTFOLIO_SKU", idea: "IDEA", hook: "HOOK", creativeCopy: "CREATIVE_COPY", direction: "DIRECTION", shotList: "SHOT_LIST", captionOne: "CAPTION_A", captionTwo: "CAPTION_B", captionThree: "CAPTION_C", referenceImage: "REFERENCE_IMAGE", referenceCredit: "REFERENCE_CREDIT" },
        },
      };
    }

    var _soAudRowSeq = 0, _soPillarRowSeq = 0;

    function audienceRowHtml(a, idx){
      a = a || { id: "", description: "", buyingSituation: "", trigger: "" };
      return '<div class="so-row" data-row="'+idx+'" style="border:1px solid var(--border);border-radius:8px;padding:10px;margin-bottom:8px">'+
        '<div style="display:flex;gap:8px;margin-bottom:6px">'+
          '<input class="form-control" placeholder="id (e.g. household-cook)" value="'+esc(a.id)+'" data-field="id" style="flex:1">'+
          '<button class="btn btn-ghost" style="padding:4px 10px" onclick="this.closest(\'.so-row\').remove()">&#10005;</button>'+
        '</div>'+
        '<textarea class="form-control" placeholder="Description" data-field="description" style="margin-bottom:6px;min-height:40px">'+esc(a.description)+'</textarea>'+
        '<textarea class="form-control" placeholder="Buying situation" data-field="buyingSituation" style="margin-bottom:6px;min-height:40px">'+esc(a.buyingSituation)+'</textarea>'+
        '<textarea class="form-control" placeholder="Trigger" data-field="trigger" style="min-height:40px">'+esc(a.trigger)+'</textarea>'+
      '</div>';
    }
    function soAddAudienceRow(){
      document.getElementById("so-audience-rows").insertAdjacentHTML("beforeend", audienceRowHtml(null, _soAudRowSeq++));
    }

    function pillarRowHtml(p, idx){
      p = p || { id: "", name: "", description: "", targetShare: 0.1 };
      return '<div class="so-row" data-row="'+idx+'" style="border:1px solid var(--border);border-radius:8px;padding:10px;margin-bottom:8px">'+
        '<div style="display:flex;gap:8px;margin-bottom:6px">'+
          '<input class="form-control" placeholder="id" value="'+esc(p.id)+'" data-field="id" style="flex:1">'+
          '<input class="form-control" placeholder="Name" value="'+esc(p.name)+'" data-field="name" style="flex:2">'+
          '<input class="form-control" type="number" step="0.01" min="0" max="1" placeholder="Target share (0-1)" value="'+esc(p.targetShare)+'" data-field="targetShare" style="width:110px">'+
          '<button class="btn btn-ghost" style="padding:4px 10px" onclick="this.closest(\'.so-row\').remove()">&#10005;</button>'+
        '</div>'+
        '<textarea class="form-control" placeholder="Description" data-field="description" style="min-height:40px">'+esc(p.description)+'</textarea>'+
      '</div>';
    }
    function soAddPillarRow(){
      document.getElementById("so-pillar-rows").insertAdjacentHTML("beforeend", pillarRowHtml(null, _soPillarRowSeq++));
    }

    function csvLine(arr){ return (arr||[]).join(", "); }
    function linesText(arr){ return (arr||[]).join("\n"); }
    function splitCsv(s){ return String(s||"").split(",").map(function(x){return x.trim();}).filter(Boolean); }
    function splitLines(s){ return String(s||"").split("\n").map(function(x){return x.trim();}).filter(Boolean); }

    function soOpenBrandForm(brandId){
      _soBrandView = brandId;
      soRenderBrandForm(brandId);
    }

    function soRenderBrandForm(brandId){
      var root = soRoot(); if(!root) return;
      var isNew = brandId === "__new__";
      var existing = isNew ? null : (window._soBrandsCache||{})[brandId];
      var b = existing || soDefaultBrandTemplate(isNew ? "" : brandId);
      _soAudRowSeq = 0; _soPillarRowSeq = 0;
      var advanced = { portfolios: b.portfolios, claimRules: b.claimRules, copyStructure: b.copyStructure, sourceVectorStoreIds: b.sourceVectorStoreIds, canva: b.canva };

      root.innerHTML =
        '<div class="section-header" style="margin-top:0">'+
          '<div><button class="btn btn-ghost" style="padding:4px 10px;font-size:11px;margin-bottom:8px" onclick="window.soOpenBrandList()">&larr; Brands</button>'+
          '<div class="section-title">'+(isNew ? "Add brand" : "Edit "+esc(b.name||b.id))+'</div></div>'+
        '</div>'+

        '<div class="att-board"><div class="bh">Basics</div>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin:6px 0 4px">Brand id (slug — lowercase, hyphens, cannot be changed later)</label>'+
          '<input class="form-control" id="so-bf-id" value="'+esc(b.id)+'" placeholder="e.g. rro"'+(isNew?'':' disabled style="opacity:.6"')+' style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Name</label>'+
          '<input class="form-control" id="so-bf-name" value="'+esc(b.name)+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Category</label>'+
          '<input class="form-control" id="so-bf-category" value="'+esc(b.category)+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Market(s) — comma-separated</label>'+
          '<input class="form-control" id="so-bf-market" value="'+esc(csvLine(b.market))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Aspirational market(s) — comma-separated</label>'+
          '<input class="form-control" id="so-bf-aspirational" value="'+esc(csvLine(b.aspirationalMarkets))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Website</label>'+
          '<input class="form-control" id="so-bf-website" value="'+esc(b.website||'')+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Google Drive folder link</label>'+
          '<input class="form-control" id="so-bf-drive" value="'+esc(b.driveFolderUrl||'')+'" placeholder="Not read by Research yet — see the integration notes" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">One-line truth (what this brand actually is)</label>'+
          '<textarea class="form-control" id="so-bf-truth" style="min-height:50px">'+esc(b.oneLineTruth)+'</textarea>'+
        '</div>'+

        '<div class="att-board"><div class="bh">Deliverables (per month)</div>'+
          '<div style="display:flex;gap:10px;margin-bottom:10px">'+
            '<div style="flex:1"><label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Reels</label><input class="form-control" type="number" min="0" id="so-bf-reel" value="'+b.deliverables.reel+'"></div>'+
            '<div style="flex:1"><label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Carousels</label><input class="form-control" type="number" min="0" id="so-bf-carousel" value="'+b.deliverables.carousel+'"></div>'+
            '<div style="flex:1"><label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Statics</label><input class="form-control" type="number" min="0" id="so-bf-static" value="'+b.deliverables.static+'"></div>'+
          '</div>'+
          '<label style="font-size:12px;display:flex;align-items:center;gap:6px"><input type="checkbox" id="so-bf-confirmed" '+(b.deliverables.confirmed?'checked':'')+'> Deliverable counts confirmed with client</label>'+
        '</div>'+

        '<div class="att-board"><div class="bh">Voice</div>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Descriptors (comma-separated, at least 3 — e.g. warm, trustworthy, practical)</label>'+
          '<input class="form-control" id="so-bf-descriptors" value="'+esc(csvLine(b.voice.descriptors))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Principles (one per line)</label>'+
          '<textarea class="form-control" id="so-bf-principles" style="min-height:60px;margin-bottom:10px">'+esc(linesText(b.voice.principles))+'</textarea>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Banned words (comma-separated)</label>'+
          '<input class="form-control" id="so-bf-bannedwords" value="'+esc(csvLine(b.voice.bannedWords))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Banned moves (one per line)</label>'+
          '<textarea class="form-control" id="so-bf-bannedmoves" style="min-height:60px;margin-bottom:10px">'+esc(linesText(b.voice.bannedMoves))+'</textarea>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Emoji rule</label>'+
          '<input class="form-control" id="so-bf-emojirule" value="'+esc(b.voice.emojiRule)+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Language rule</label>'+
          '<input class="form-control" id="so-bf-languagerule" value="'+esc(b.voice.languageRule)+'">'+
        '</div>'+

        '<div class="att-board"><div class="bh">Audiences <span class="tag">at least 1</span></div>'+
          '<div id="so-audience-rows">'+(b.audiences.length ? b.audiences.map(function(a){ return audienceRowHtml(a, _soAudRowSeq++); }).join("") : audienceRowHtml(null, _soAudRowSeq++))+'</div>'+
          '<button class="btn btn-ghost" style="font-size:12px" onclick="window.soAddAudienceRow()">+ Add audience</button>'+
        '</div>'+

        '<div class="att-board"><div class="bh">Visual</div>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Feel (comma-separated, at least 3)</label>'+
          '<input class="form-control" id="so-bf-feel" value="'+esc(csvLine(b.visual.feel))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Palette (comma-separated)</label>'+
          '<input class="form-control" id="so-bf-palette" value="'+esc(csvLine(b.visual.palette))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Principles (one per line, at least 1)</label>'+
          '<textarea class="form-control" id="so-bf-visprinciples" style="min-height:60px;margin-bottom:10px">'+esc(linesText(b.visual.principles))+'</textarea>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Avoid (one per line, at least 1)</label>'+
          '<textarea class="form-control" id="so-bf-visavoid" style="min-height:60px">'+esc(linesText(b.visual.avoid))+'</textarea>'+
        '</div>'+

        '<div class="att-board"><div class="bh">Content pillars <span class="tag">at least 1</span></div>'+
          '<div id="so-pillar-rows">'+(b.pillars.length ? b.pillars.map(function(p){ return pillarRowHtml(p, _soPillarRowSeq++); }).join("") : pillarRowHtml(null, _soPillarRowSeq++))+'</div>'+
          '<button class="btn btn-ghost" style="font-size:12px" onclick="window.soAddPillarRow()">+ Add pillar</button>'+
        '</div>'+

        '<div class="att-board"><div class="bh">Other</div>'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Competitors (comma-separated — research only, never named in copy)</label>'+
          '<input class="form-control" id="so-bf-competitors" value="'+esc(csvLine(b.competitors))+'" style="margin-bottom:10px">'+
          '<label style="display:block;font-size:11px;color:var(--muted);margin-bottom:4px">Known unknowns (one per line)</label>'+
          '<textarea class="form-control" id="so-bf-unknowns" style="min-height:60px">'+esc(linesText(b.knownUnknowns))+'</textarea>'+
        '</div>'+

        '<details class="att-board"><summary class="bh" style="cursor:pointer;list-style:none">Advanced (portfolios, claim rules, copy structure, Canva) &#9662;</summary>'+
          '<div style="font-size:12px;color:var(--muted);margin:8px 0">Most brands don\'t need this — RRO is the one that does. Edit as JSON; it\'s validated the same as everything else on save.</div>'+
          '<textarea class="form-control" id="so-bf-advanced" style="min-height:220px;font-family:monospace;font-size:12px">'+esc(JSON.stringify(advanced, null, 2))+'</textarea>'+
        '</details>'+

        '<div class="att-board">'+
          '<div id="so-bf-error" style="color:var(--red);font-size:12px;margin-bottom:10px;display:none;white-space:pre-wrap"></div>'+
          '<div style="display:flex;gap:8px">'+
            '<button class="btn btn-ghost" style="flex:1" onclick="window.soOpenBrandList()">Cancel</button>'+
            '<button class="btn btn-primary" style="flex:1" id="so-bf-submit" onclick="window.soSubmitBrandForm(\''+esc(brandId)+'\')">Save brand</button>'+
          '</div>'+
        '</div>';
    }

    async function soSubmitBrandForm(brandIdArg){
      var isNew = brandIdArg === "__new__";
      var errEl = document.getElementById("so-bf-error");
      var btn = document.getElementById("so-bf-submit");
      if(errEl){ errEl.style.display="none"; errEl.textContent=""; }

      var id = document.getElementById("so-bf-id").value.trim();
      if(!/^[a-z0-9-]+$/.test(id)){
        if(errEl){ errEl.textContent="Brand id must be lowercase letters, numbers or hyphens."; errEl.style.display="block"; }
        return;
      }

      var audiences = Array.from(document.querySelectorAll("#so-audience-rows .so-row")).map(function(row){
        return {
          id: row.querySelector('[data-field="id"]').value.trim(),
          description: row.querySelector('[data-field="description"]').value.trim(),
          buyingSituation: row.querySelector('[data-field="buyingSituation"]').value.trim(),
          trigger: row.querySelector('[data-field="trigger"]').value.trim(),
        };
      }).filter(function(a){ return a.id; });

      var pillars = Array.from(document.querySelectorAll("#so-pillar-rows .so-row")).map(function(row){
        return {
          id: row.querySelector('[data-field="id"]').value.trim(),
          name: row.querySelector('[data-field="name"]').value.trim(),
          description: row.querySelector('[data-field="description"]').value.trim(),
          targetShare: parseFloat(row.querySelector('[data-field="targetShare"]').value) || 0,
        };
      }).filter(function(p){ return p.id; });

      var advanced;
      try {
        advanced = JSON.parse(document.getElementById("so-bf-advanced").value || "{}");
      } catch(e) {
        if(errEl){ errEl.textContent="The Advanced JSON isn't valid: "+e.message; errEl.style.display="block"; }
        return;
      }

      var config = {
        schemaVersion: "1.0",
        id: id,
        name: document.getElementById("so-bf-name").value.trim(),
        category: document.getElementById("so-bf-category").value.trim(),
        market: splitCsv(document.getElementById("so-bf-market").value),
        aspirationalMarkets: splitCsv(document.getElementById("so-bf-aspirational").value),
        website: document.getElementById("so-bf-website").value.trim() || null,
        driveFolderUrl: document.getElementById("so-bf-drive").value.trim() || null,
        oneLineTruth: document.getElementById("so-bf-truth").value.trim(),
        deliverables: {
          reel: parseInt(document.getElementById("so-bf-reel").value, 10) || 0,
          carousel: parseInt(document.getElementById("so-bf-carousel").value, 10) || 0,
          static: parseInt(document.getElementById("so-bf-static").value, 10) || 0,
          confirmed: document.getElementById("so-bf-confirmed").checked,
        },
        voice: {
          descriptors: splitCsv(document.getElementById("so-bf-descriptors").value),
          principles: splitLines(document.getElementById("so-bf-principles").value),
          bannedWords: splitCsv(document.getElementById("so-bf-bannedwords").value),
          bannedMoves: splitLines(document.getElementById("so-bf-bannedmoves").value),
          emojiRule: document.getElementById("so-bf-emojirule").value.trim(),
          languageRule: document.getElementById("so-bf-languagerule").value.trim(),
        },
        audiences: audiences,
        visual: {
          feel: splitCsv(document.getElementById("so-bf-feel").value),
          palette: splitCsv(document.getElementById("so-bf-palette").value),
          principles: splitLines(document.getElementById("so-bf-visprinciples").value),
          avoid: splitLines(document.getElementById("so-bf-visavoid").value),
        },
        pillars: pillars,
        competitors: splitCsv(document.getElementById("so-bf-competitors").value),
        knownUnknowns: splitLines(document.getElementById("so-bf-unknowns").value),
        portfolios: advanced.portfolios || [],
        claimRules: advanced.claimRules || [],
        copyStructure: advanced.copyStructure || null,
        sourceVectorStoreIds: advanced.sourceVectorStoreIds || [],
        canva: advanced.canva || soDefaultBrandTemplate().canva,
      };

      if(btn){ btn.disabled=true; btn.textContent="Saving…"; }
      try {
        var res = await fetch("/.netlify/functions/strategy-brand-save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ brandId: id, config: config }),
        });
        var data = await res.json().catch(function(){ return {}; });
        if(!res.ok){
          var msg = data.error || "Could not save this brand.";
          if(Array.isArray(data.issues) && data.issues.length){
            msg += "\n\n" + data.issues.map(function(i){ return "• "+i.path+": "+i.message; }).join("\n");
          }
          throw new Error(msg);
        }
        window.soOpenBrandList();
      } catch(e) {
        if(errEl){ errEl.textContent = e.message || String(e); errEl.style.display="block"; }
      } finally {
        if(btn){ btn.disabled=false; btn.textContent="Save brand"; }
      }
    }

    window.soOpenPage = soOpenPage;
    window.soOpenNewRunModal = soOpenNewRunModal;
    window.soCloseNewRunModal = soCloseNewRunModal;
    window.soSubmitNewRun = soSubmitNewRun;
    window.soSetRunListView = soSetRunListView;
    window.soArchiveRun = soArchiveRun;
    window.soRestoreRun = soRestoreRun;
    window.soPurgeRun = soPurgeRun;
    window.soOpenRun = soOpenRun;
    window.soBackToList = soBackToList;
    window.soDecide = soDecide;
    window.soRetryStage = soRetryStage;
    window.soReopenStage = soReopenStage;
    window.soCreateTeamTasks = soCreateTeamTasks;
    window.soUpdateDeckPage = soUpdateDeckPage;
    window.soSuggestSimilar = soSuggestSimilar;
    window.soToggleRefineBox = soToggleRefineBox;
    window.soSendRefine = soSendRefine;
    window.soDiscardConcept = soDiscardConcept;
    window.soAcceptConceptCandidate = soAcceptConceptCandidate;
    window.soRejectConceptCandidate = soRejectConceptCandidate;
    window.soRetryConceptCandidate = soRetryConceptCandidate;
    window.soReplaceCopyAsset = soReplaceCopyAsset;
    window.soToggleAssetLock = soToggleAssetLock;
    window.soOpenBrandList = soOpenBrandList;
    window.soBackToRunsFromBrands = soBackToRunsFromBrands;
    window.soOpenBrandForm = soOpenBrandForm;
    window.soAddAudienceRow = soAddAudienceRow;
    window.soAddPillarRow = soAddPillarRow;
    window.soSubmitBrandForm = soSubmitBrandForm;
  })();
