// Builds a downloadable .pptx from a validated DeckSpec (see contracts.js's DeckSpecSchema)
// — one slide per deck page, containing exactly what the brief asked for: the concept, the
// copy, the creative direction, the reference credit, the owner, and production status.
//
// This deck export is self-contained: pptxgenjs turns the validated checkpoint into a
// file without an external publishing service, expiring OAuth connection or template.
"use strict";
const PptxGenJS = require("pptxgenjs");

const BRAND_ACCENT = "FF6D29"; // Loona's --accent, without the leading '#' (pptxgenjs style)
const TEXT_DARK = "1A1A1A";
const TEXT_MUTED = "666666";
const RULE_COLOR = "E5E5E5";

// pptxgenjs's addText() only reliably starts a new paragraph when an array item's own
// options set breakLine:true — an embedded "\n" inside a single item's text string is NOT
// a dependable paragraph separator (confirmed empirically: it sometimes merges into the
// previous item's paragraph instead of starting a new one). So every logical line is built
// as its own array item with breakLine:true, rather than joining lines with "\n" and
// hoping pptxgenjs splits them.
function line(text, opts) {
  return { text: text, options: Object.assign({ breakLine: true }, opts || {}) };
}
function label(text, opts) {
  return line(text.toUpperCase(), Object.assign({ fontSize: 9, color: BRAND_ACCENT, bold: true, charSpacing: 1 }, opts || {}));
}
// Splits a possibly-multi-line string into one line() per row (dropping blank rows from
// double newlines), each carrying the same style options.
function bodyLines(text, opts) {
  return String(text || "").split("\n").map((row) => row.trim()).filter(Boolean).map((row) => line(row, opts));
}

function buildDeckPptx(deck) {
  const pres = new PptxGenJS();
  pres.defineLayout({ name: "LOONA_WIDE", width: 13.33, height: 7.5 });
  pres.layout = "LOONA_WIDE";
  pres.author = "Loona Hub — Strategy OS";
  pres.title = deck.title || "Monthly strategy deck";

  // Cover slide — same info the Hub's own deck review header shows.
  const cover = pres.addSlide();
  cover.background = { color: "FFFFFF" };
  cover.addShape("rect", { x: 0, y: 0, w: 13.33, h: 0.18, fill: { color: BRAND_ACCENT } });
  cover.addText(deck.title || "Monthly strategy deck", { x: 0.7, y: 2.8, w: 12, h: 1, fontSize: 36, bold: true, color: TEXT_DARK });
  if (deck.subtitle) {
    cover.addText(deck.subtitle, { x: 0.7, y: 3.7, w: 12, h: 0.6, fontSize: 16, color: TEXT_MUTED });
  }
  cover.addText(`${deck.pages.length} pages · Generated by Loona Hub Strategy OS`, { x: 0.7, y: 6.7, w: 12, h: 0.4, fontSize: 10, color: TEXT_MUTED });

  deck.pages.forEach((page) => {
    const slide = pres.addSlide();
    slide.background = { color: "FFFFFF" };
    slide.addShape("rect", { x: 0, y: 0, w: 13.33, h: 0.55, fill: { color: BRAND_ACCENT } });
    slide.addText(
      `Page ${page.pageNumber} · ${page.format.toUpperCase()} · ${page.portfolioAndSku}`,
      { x: 0.5, y: 0.06, w: 12.3, h: 0.4, fontSize: 13, bold: true, color: "FFFFFF" }
    );

    // Idea + hook, top band.
    slide.addText(page.idea, { x: 0.5, y: 0.75, w: 12.3, h: 0.4, fontSize: 15, bold: true, color: TEXT_DARK });
    slide.addText(`"${page.hook}"`, { x: 0.5, y: 1.18, w: 12.3, h: 0.5, fontSize: 13, italic: true, color: BRAND_ACCENT });
    slide.addShape("line", { x: 0.5, y: 1.72, w: 12.3, h: 0, line: { color: RULE_COLOR, width: 1 } });

    // Two columns: copy (left) / direction (right). Each section is a label() line
    // followed by bodyLines() for its (possibly multi-paragraph) content, with a blank
    // spacer line between sections — every line is its own explicit array item so the
    // paragraph structure is deterministic regardless of how much text each field holds.
    const colTop = 1.9;
    const colH = 4.1;
    const spacer = line(" ", { fontSize: 4 });
    slide.addText(
      [].concat(
        label("Creative copy"), bodyLines(page.creativeCopy, { fontSize: 11, color: TEXT_DARK }), spacer,
        label("Captions"), bodyLines([page.captionOne, page.captionTwo, page.captionThree].filter(Boolean).join("\n"), { fontSize: 10, color: TEXT_DARK })
      ),
      { x: 0.5, y: colTop, w: 6.1, h: colH, valign: "top", fontSize: 11, color: TEXT_DARK }
    );
    slide.addText(
      [].concat(
        label("Direction"), bodyLines(page.direction, { fontSize: 11, color: TEXT_DARK }), spacer,
        label("Shot list"), bodyLines(page.shotList, { fontSize: 10, color: TEXT_DARK }), spacer,
        label("Reference"), [line(page.referenceCredit || "No reference on file", { fontSize: 10, color: TEXT_MUTED, italic: true })]
      ),
      { x: 6.9, y: colTop, w: 5.9, h: colH, valign: "top", fontSize: 11, color: TEXT_DARK }
    );

    if (page.productionNotes) {
      slide.addText(page.productionNotes, { x: 0.5, y: 6.1, w: 12.3, h: 0.5, fontSize: 9, italic: true, color: TEXT_MUTED });
    }

    // Footer: owner + production status, same fields Hub's deck review lets you edit.
    slide.addShape("line", { x: 0.5, y: 6.65, w: 12.3, h: 0, line: { color: RULE_COLOR, width: 1 } });
    const statusLabel = { not_started: "Not started", in_progress: "In progress", ready_for_review: "Ready for review", complete: "Complete" }[page.productionStatus] || page.productionStatus || "Not started";
    slide.addText(
      [
        { text: "OWNER  ", options: { bold: true, color: TEXT_MUTED } },
        { text: (page.owner || "Unassigned") + "      ", options: { color: TEXT_DARK } },
        { text: "STATUS  ", options: { bold: true, color: TEXT_MUTED } },
        { text: statusLabel, options: { color: TEXT_DARK } },
      ],
      { x: 0.5, y: 6.8, w: 12.3, h: 0.35, fontSize: 10 }
    );
  });

  return pres.write({ outputType: "nodebuffer" });
}

module.exports = { buildDeckPptx };
